import {
  Crown, Landmark, Building2, Users, Briefcase, DollarSign, ShoppingCart,
  TrendingUp, Package, Truck, Wrench, Cpu, Megaphone, Headphones, Scale,
  Factory, FlaskConical, HardHat, BookOpen, Shield, Stethoscope, ClipboardList,
  BarChart3, FileText, Handshake, Palette, Code2, Globe, Wallet, Receipt,
  UserCog, Building, Store, PenTool, Send, LifeBuoy, Sparkles,
  Banknote, CreditCard, PiggyBank, Calculator, LineChart, PieChart, Target,
  Rocket, Lightbulb, Award, Trophy, Star, Heart, Gem, Anchor, Plane, Ship,
  Car, Bike, Bus, Train, Warehouse, Boxes, ClipboardCheck, CalendarDays,
  Mail, Phone, MessageCircle, Video, Camera, Mic, Music, Radio, Tv,
  Server, Database, Cloud, HardDrive, Network, Wifi, Lock, KeyRound,
  Fingerprint, Eye, Search, Filter, Settings, Cog, Hammer, Drill, Ruler,
  Paintbrush, Scissors, Gift, Tag, Percent, Trees, Leaf, Flame, Droplet, Zap, Sun,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const DEPT_ICONS: { key: string; icon: LucideIcon; label_ar: string; label_en: string }[] = [
  { key: "crown", icon: Crown, label_ar: "إدارة عليا", label_en: "Executive" },
  { key: "landmark", icon: Landmark, label_ar: "إدارة عامة", label_en: "General" },
  { key: "building2", icon: Building2, label_ar: "إدارة", label_en: "Department" },
  { key: "building", icon: Building, label_ar: "فرع", label_en: "Branch" },
  { key: "users", icon: Users, label_ar: "موارد بشرية", label_en: "HR" },
  { key: "userCog", icon: UserCog, label_ar: "شؤون الموظفين", label_en: "Staff Affairs" },
  { key: "briefcase", icon: Briefcase, label_ar: "أعمال", label_en: "Business" },
  { key: "dollar", icon: DollarSign, label_ar: "مالية", label_en: "Finance" },
  { key: "wallet", icon: Wallet, label_ar: "خزينة", label_en: "Treasury" },
  { key: "receipt", icon: Receipt, label_ar: "محاسبة", label_en: "Accounting" },
  { key: "cart", icon: ShoppingCart, label_ar: "مشتريات", label_en: "Purchasing" },
  { key: "trending", icon: TrendingUp, label_ar: "مبيعات", label_en: "Sales" },
  { key: "store", icon: Store, label_ar: "منافذ بيع", label_en: "Retail" },
  { key: "package", icon: Package, label_ar: "مخازن", label_en: "Warehouse" },
  { key: "truck", icon: Truck, label_ar: "لوجستيات", label_en: "Logistics" },
  { key: "factory", icon: Factory, label_ar: "إنتاج", label_en: "Production" },
  { key: "wrench", icon: Wrench, label_ar: "صيانة", label_en: "Maintenance" },
  { key: "hardhat", icon: HardHat, label_ar: "مشاريع", label_en: "Projects" },
  { key: "cpu", icon: Cpu, label_ar: "تقنية المعلومات", label_en: "IT" },
  { key: "code", icon: Code2, label_ar: "تطوير", label_en: "Development" },
  { key: "megaphone", icon: Megaphone, label_ar: "تسويق", label_en: "Marketing" },
  { key: "palette", icon: Palette, label_ar: "تصميم", label_en: "Design" },
  { key: "pen", icon: PenTool, label_ar: "محتوى", label_en: "Content" },
  { key: "send", icon: Send, label_ar: "علاقات عامة", label_en: "PR" },
  { key: "headphones", icon: Headphones, label_ar: "خدمة عملاء", label_en: "Support" },
  { key: "lifebuoy", icon: LifeBuoy, label_ar: "دعم فني", label_en: "Help Desk" },
  { key: "handshake", icon: Handshake, label_ar: "شراكات", label_en: "Partnerships" },
  { key: "scale", icon: Scale, label_ar: "شؤون قانونية", label_en: "Legal" },
  { key: "file", icon: FileText, label_ar: "وثائق", label_en: "Documents" },
  { key: "clipboard", icon: ClipboardList, label_ar: "تخطيط", label_en: "Planning" },
  { key: "chart", icon: BarChart3, label_ar: "تقارير", label_en: "Reports" },
  { key: "flask", icon: FlaskConical, label_ar: "جودة", label_en: "Quality" },
  { key: "book", icon: BookOpen, label_ar: "تدريب", label_en: "Training" },
  { key: "shield", icon: Shield, label_ar: "أمن", label_en: "Security" },
  { key: "stethoscope", icon: Stethoscope, label_ar: "طبي", label_en: "Medical" },
  { key: "globe", icon: Globe, label_ar: "دولي", label_en: "International" },
  { key: "sparkles", icon: Sparkles, label_ar: "ابتكار", label_en: "Innovation" },
  { key: "banknote", icon: Banknote, label_ar: "نقدية", label_en: "Cash" },
  { key: "creditcard", icon: CreditCard, label_ar: "مدفوعات", label_en: "Payments" },
  { key: "piggybank", icon: PiggyBank, label_ar: "توفير", label_en: "Savings" },
  { key: "calculator", icon: Calculator, label_ar: "تدقيق", label_en: "Audit" },
  { key: "linechart", icon: LineChart, label_ar: "تحليلات", label_en: "Analytics" },
  { key: "piechart", icon: PieChart, label_ar: "إحصاءات", label_en: "Statistics" },
  { key: "target", icon: Target, label_ar: "استراتيجية", label_en: "Strategy" },
  { key: "rocket", icon: Rocket, label_ar: "نمو", label_en: "Growth" },
  { key: "lightbulb", icon: Lightbulb, label_ar: "أفكار", label_en: "Ideas" },
  { key: "award", icon: Award, label_ar: "جوائز", label_en: "Awards" },
  { key: "trophy", icon: Trophy, label_ar: "إنجازات", label_en: "Achievements" },
  { key: "star", icon: Star, label_ar: "تميّز", label_en: "Excellence" },
  { key: "heart", icon: Heart, label_ar: "رعاية", label_en: "Care" },
  { key: "gem", icon: Gem, label_ar: "VIP", label_en: "VIP" },
  { key: "anchor", icon: Anchor, label_ar: "بحري", label_en: "Marine" },
  { key: "plane", icon: Plane, label_ar: "طيران", label_en: "Aviation" },
  { key: "ship", icon: Ship, label_ar: "شحن بحري", label_en: "Shipping" },
  { key: "car", icon: Car, label_ar: "مركبات", label_en: "Fleet" },
  { key: "bike", icon: Bike, label_ar: "توصيل", label_en: "Delivery" },
  { key: "bus", icon: Bus, label_ar: "نقل", label_en: "Transport" },
  { key: "train", icon: Train, label_ar: "سكك", label_en: "Rail" },
  { key: "warehouse", icon: Warehouse, label_ar: "مستودع", label_en: "Warehouse" },
  { key: "boxes", icon: Boxes, label_ar: "مخزون", label_en: "Inventory" },
  { key: "clipboardcheck", icon: ClipboardCheck, label_ar: "متابعة", label_en: "Follow-up" },
  { key: "calendar", icon: CalendarDays, label_ar: "جدولة", label_en: "Scheduling" },
  { key: "mail", icon: Mail, label_ar: "بريد", label_en: "Mail" },
  { key: "phone", icon: Phone, label_ar: "اتصالات", label_en: "Telecom" },
  { key: "message", icon: MessageCircle, label_ar: "محادثات", label_en: "Chat" },
  { key: "video", icon: Video, label_ar: "فيديو", label_en: "Video" },
  { key: "camera", icon: Camera, label_ar: "تصوير", label_en: "Photography" },
  { key: "mic", icon: Mic, label_ar: "بودكاست", label_en: "Podcast" },
  { key: "music", icon: Music, label_ar: "موسيقى", label_en: "Music" },
  { key: "radio", icon: Radio, label_ar: "إذاعة", label_en: "Broadcast" },
  { key: "tv", icon: Tv, label_ar: "إعلام", label_en: "Media" },
  { key: "server", icon: Server, label_ar: "خوادم", label_en: "Servers" },
  { key: "database", icon: Database, label_ar: "قواعد بيانات", label_en: "Database" },
  { key: "cloud", icon: Cloud, label_ar: "سحابة", label_en: "Cloud" },
  { key: "harddrive", icon: HardDrive, label_ar: "تخزين", label_en: "Storage" },
  { key: "network", icon: Network, label_ar: "شبكات", label_en: "Network" },
  { key: "wifi", icon: Wifi, label_ar: "اتصال", label_en: "Connectivity" },
  { key: "lock", icon: Lock, label_ar: "حماية", label_en: "Protection" },
  { key: "key", icon: KeyRound, label_ar: "صلاحيات", label_en: "Access" },
  { key: "fingerprint", icon: Fingerprint, label_ar: "هوية", label_en: "Identity" },
  { key: "eye", icon: Eye, label_ar: "مراقبة", label_en: "Monitoring" },
  { key: "search", icon: Search, label_ar: "بحث", label_en: "Research" },
  { key: "filter", icon: Filter, label_ar: "تصفية", label_en: "Filtering" },
  { key: "settings", icon: Settings, label_ar: "إعدادات", label_en: "Settings" },
  { key: "cog", icon: Cog, label_ar: "عمليات", label_en: "Operations" },
  { key: "hammer", icon: Hammer, label_ar: "تنفيذ", label_en: "Execution" },
  { key: "drill", icon: Drill, label_ar: "حفر", label_en: "Drilling" },
  { key: "ruler", icon: Ruler, label_ar: "قياس", label_en: "Measurement" },
  { key: "paintbrush", icon: Paintbrush, label_ar: "ديكور", label_en: "Decor" },
  { key: "scissors", icon: Scissors, label_ar: "تفصيل", label_en: "Tailoring" },
  { key: "gift", icon: Gift, label_ar: "هدايا", label_en: "Gifts" },
  { key: "tag", icon: Tag, label_ar: "أسعار", label_en: "Pricing" },
  { key: "percent", icon: Percent, label_ar: "عروض", label_en: "Promotions" },
  { key: "trees", icon: Trees, label_ar: "بيئة", label_en: "Environment" },
  { key: "leaf", icon: Leaf, label_ar: "استدامة", label_en: "Sustainability" },
  { key: "flame", icon: Flame, label_ar: "طاقة", label_en: "Energy" },
  { key: "droplet", icon: Droplet, label_ar: "مياه", label_en: "Water" },
  { key: "zap", icon: Zap, label_ar: "كهرباء", label_en: "Electricity" },
  { key: "sun", icon: Sun, label_ar: "طاقة شمسية", label_en: "Solar" },
];

const MAP: Record<string, LucideIcon> = Object.fromEntries(DEPT_ICONS.map((i) => [i.key, i.icon]));

export function getDeptIcon(key: string | null | undefined, depth = 0): LucideIcon {
  if (key && MAP[key]) return MAP[key];
  // fallback by depth
  if (depth === 0) return Crown;
  if (depth === 1) return Landmark;
  if (depth === 2) return Building2;
  return Briefcase;
}
